# These are supported funding model platforms

ko_fi: v1rtl
liberapay: v1rtl
custom: ["https://stakes.social/0x14308514785B216904a41aB817282d25425Cce39", "https://paypal.me/v1rtl", "https://qiwi.com/n/V1RTL", "https://yoomoney.ru/to/410014774355272"]
issuehunt: talentlessguy
